# Generated by Django 3.1.6 on 2021-02-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atracao',
            options={'verbose_name': 'atração', 'verbose_name_plural': 'atrações'},
        ),
    ]
